parameters:
  param1: ''

stages:
  - stage: BuildApp
    displayName: Build Apps
    jobs:
      - job: MyBuildingJob
        displayName: My building job in a template ${{ paramters.param1 }}
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'sleep 30'
          - script: ls -l
            displayName: listing files            
          - script: echo i am building my app
            displayName: build step
      - job: MyTestingJob
        displayName: My testing job
        dependsOn: MyBuildingJob
        steps:
          - script: echo i am testing my app
            displayName: testing step
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo ''I am testing'''
